//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konstruction.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveDirectorySetting
    {
        public int ID { get; set; }
        public int Type { get; set; }
        public string DC { get; set; }
        public string Path { get; set; }
        public string DefaultLogin { get; set; }
        public string DefaultPassword { get; set; }
    }
}
