//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konstruction.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KonstructionEntities : DbContext
    {
        public KonstructionEntities()
            : base("name=KonstructionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActiveDirectorySetting> ActiveDirectorySetting { get; set; }
        public virtual DbSet<Datenformat> Datenformat { get; set; }
        public virtual DbSet<Einfügefehler> Einfügefehler { get; set; }
        public virtual DbSet<Ersteller> Ersteller { get; set; }
        public virtual DbSet<Kunde_zg_revision> Kunde_zg_revision { get; set; }
        public virtual DbSet<Kunde_zuweisung_ZSB_Nr> Kunde_zuweisung_ZSB_Nr { get; set; }
        public virtual DbSet<Kunden_Teile_nr> Kunden_Teile_nr { get; set; }
        public virtual DbSet<Last_Pass_Teile_nr> Last_Pass_Teile_nr { get; set; }
        public virtual DbSet<Pass_Kunde_zuweisung_ZSB_Nr> Pass_Kunde_zuweisung_ZSB_Nr { get; set; }
        public virtual DbSet<Pass_Teile_nr> Pass_Teile_nr { get; set; }
        public virtual DbSet<Pass_zg_revision> Pass_zg_revision { get; set; }
        public virtual DbSet<Pass_zuweisung_ZSB_Nr> Pass_zuweisung_ZSB_Nr { get; set; }
    }
}
