//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konstruction.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kunde_zuweisung_ZSB_Nr
    {
        public string k_unter_zsb_zg_nr { get; set; }
        public string k_zg_nr { get; set; }
        public int ID { get; set; }
        public Nullable<int> k_unter_zsb_zg_id { get; set; }
        public Nullable<int> k_zg_id { get; set; }
    }
}
