//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konstruction.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kunde_zg_revision
    {
        public string k_zg_nr { get; set; }
        public Nullable<System.DateTime> k_rev_date { get; set; }
        public string k_lfd_nr { get; set; }
        public string k_rev_record { get; set; }
        public int ID { get; set; }
        public Nullable<int> k_zg_id { get; set; }
    }
}
