//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konstruction.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pass_zuweisung_ZSB_Nr
    {
        public string p_unter_zsb_zg_nr { get; set; }
        public string p_zg_nr { get; set; }
        public int ID { get; set; }
        public Nullable<int> p_unter_zsb_zg_id { get; set; }
        public Nullable<int> p_zg_id { get; set; }
    }
}
