//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konstruction.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pass_zg_revision
    {
        public string p_zg_nr { get; set; }
        public Nullable<System.DateTime> p_rev_date { get; set; }
        public string p_lfd_nr { get; set; }
        public string p_rev_record { get; set; }
        public int ID { get; set; }
        public Nullable<int> p_zg_id { get; set; }
    }
}
